api:
  name: "prenotami-esteri"
  port: 9291
context: "local"

web_driver:
  chrome_binary: "/Applications/Chromium.app/Contents/MacOS/Chromium"
  firefox_binary: "/Applications/Firefox.app/Contents/MacOS/firefox-bin"
  chromium:
    cache_dir: "/tmp/chromium/cache-dir"
    data_path: "/tmp/chromium/data-path"
  firefox:
    cache_dir: "/tmp/firefox/cache-dir"
  cache:
    max_entries: 20
    max_age:
      seconds: 600

db:
  engine: ${DB_ENGINE}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  host: ${DB_HOST}
  port: ${DB_PORT}
  schema: ${DB_SCHEMA}

crawling:
  # Default for all bots
  parallel_factor: 1
  headers:
    user_agent: "Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0"
  max_retry_task: 0
  max_retry_proxy: 3
  data_base_path: "/tmp/htmls"
  screenshot:
    base_path: "/tmp/screenshots"
    page_ready_timeout_millis: 10000
    resolution_width: 320
    resolution_height: 192
    quality: 25
    type: "none"
  # Config for particulars
  basic_controller_config:
    webdriver_type: "firefox"

log:
  rotate:
    enabled: true
    path_file: "/tmp/logs"
    max_size: 10485760  # 1024*1024*10 = 10 MB
    backup_count: 15

  console:
    enabled: true

  level: 10 # CRITICAL = 50, ERROR = 40, WARNING = 30, INFO = 20, DEBUG = 10
